name: Dev Builds

on: [workflow_call, pull_request, push]

jobs:
  tests: # runs on linux and windows
    uses: ./.github/workflows/tests.yml
    secrets: inherit
  build: # runs on linux
    uses: ./.github/workflows/build.yml
    secrets: inherit
#    # [FEATURE] MIXIN_AUDITOR
#    with:
#      mixin_audit: true