name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true
        default: 'x.x.x'
      release_type:
        description: 'alpha/beta/release'
        required: true
        type: choice
        default: 'release'
        options:
          - 'release'
          - 'beta'
          - 'alpha'
      change_log:
        description: 'changelog'
        required: false
        default: ''

env:
    MAIN_MINECRAFT_VERSION: 1.19.3

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Check Environment Variables
        run: env

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: configure gradle
        uses: gradle/wrapper-validation-action@v1

      - name: Grant execute permission for gradlew
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x gradlew

      - name: Build 1
        run: ./gradlew build

      - name: Build 2
        run: ./gradlew build

      - name: Publish (CurseForge/Modrinth/Github)
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          curseforge-id: 639211
          curseforge-token: ${{secrets.CURSEFORGE_TOKEN}}

          modrinth-id: k68glP2e
          modrinth-token: ${{secrets.MODRINTH_TOKEN}}
          modrinth-unfeature-mode: none
          modrinth-featured: false

          github-tag: v${{inputs.version}}
          github-token: ${{secrets.GH_TOKEN}}
          github-commitish: 1.19.3

          files: Merged/*.jar

          name: AutoModpack ${{inputs.version}} ${{env.MAIN_MINECRAFT_VERSION}}
          version: ${{inputs.version}}
          version-type: ${{inputs.release_type}}
          changelog: ${{inputs.change_log}}

          loaders: |
            fabric
            quilt
          game-versions: |
            1.19.3
          dependencies: |
            fabric-api | recommends | *
            qsl | recommends | *
          java: 17